fixup: check-chart-versions-bump.yml

diff --git a/.github/workflows/check-chart-versions-bump.yml b/.github/workflows/check-chart-versions-bump.yml
--- a/.github/workflows/check-chart-versions-bump.yml
+++ b/.github/workflows/check-chart-versions-bump.yml
@@ -23,17 +23,23 @@ jobs:
       - id: check_bump
         name: Check if chart version has been bumped
         run: |
-          git checkout -b $GITHUB_BASE_REF
-          git checkout -b $GITHUB_HEAD_REF
+          git fetch --quiet origin pull/${{ github.event.pull_request.number }}/head:pr-branch
+          git fetch --quiet origin ${{ github.event.pull_request.base.ref }}:target-branch
           
+          notBumped=0
+
           for folder in $modified_chart_folders; do
-            MAIN_CHART_VERSION=$(git show $GITHUB_BASE_REF:charts/$folder/Chart.yaml | grep "^version:")
-            PR_CHART_VERSION=$(git show $GITHUB_HEAD_REF:charts/$folder/Chart.yaml | grep "^version:")
-            
-            if [ "$MAIN_CHART_VERSION" != "$PR_CHART_VERSION" ]; then
-              echo "ERROR: the version '$PR_CHART_VERSION' of the '${folder}' chart hasn't been bumped."
-              exit 1
+            MAIN_CHART_VERSION=$(git show target-branch:charts/$folder/Chart.yaml | grep "^version:" | cut -d " " -f 2)
+            PR_CHART_VERSION=$(git show pr-branch:charts/$folder/Chart.yaml | grep "^version:" | cut -d " " -f 2)
+
+            if [ "$MAIN_CHART_VERSION" == "$PR_CHART_VERSION" ]; then
+              echo "ERROR: the version of the '${folder}' chart hasn't been bumped: '$PR_CHART_VERSION'."
+              ((notBumped++))
             fi
 
-            echo "The version of the '${folder}' chart has been bumped."
+            echo "Info: the version of the '${folder}' chart has been bumped from '$MAIN_CHART_VERSION' to '$PR_CHART_VERSION'."
           done
+
+          if [ "$notBumped" -gt 0 ]; then
+            exit 1
+          fi
